# Generated by Django 4.1.7 on 2023-03-05 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import images_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ImageField(upload_to=images_app.models.get_upload_path)),
                ('binary_image', models.TextField(blank=True, null=True)),
                ('binary_image_expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=64)),
                ('generate_binary_image', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PlanThumbnailSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='images_app.plan')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='images_app.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThumbnailSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('plans', models.ManyToManyField(through='images_app.PlanThumbnailSize', to='images_app.plan')),
            ],
        ),
        migrations.AddField(
            model_name='planthumbnailsize',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images_app.thumbnailsize'),
        ),
        migrations.AddField(
            model_name='plan',
            name='thumbnail_sizes',
            field=models.ManyToManyField(through='images_app.PlanThumbnailSize', to='images_app.thumbnailsize'),
        ),
        migrations.CreateModel(
            name='FileLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(default='pustylink')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='images_app.file')),
                ('thumbnail_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images_app.thumbnailsize')),
            ],
        ),
    ]
